all:
  dbformextraplugin:
    include_jquery:      true
    jquery_path:         /cre8FormPlugin/jquery/
    jquery_version:      jquery-1.2.6.min.js
    jqueryui_path:       /cre8FormPlugin/jquery_ui/js/
    jqueryui_path_css:   /cre8FormPlugin/jquery_ui/css/
    datetime_path_js:    /cre8FormPlugin/datetime/js/
    datetime_path_css:   /cre8FormPlugin/datetime/css/
  
  datepicker:
    output_format: d.m.Y
    output_sf_format: dd.MM.yyyy
  
  captcha:
    length: 4
    width: 120
    height: 40

  tinymce:
    skin: o2k7
    dialog_type: window
    entity_encoding: raw
    relative_urls: 'false'
    gecko_spellcheck: 'true'
    plugins: 'safari,save,pagebreak,style,layer,table,advimage,advlink,emotions,iespell,insertdatetime,preview,media,searchreplace,print,paste,directionality,fullscreen,noneditable,visualchars,nonbreaking,xhtmlxtras,template'
    
    theme_advanced_buttons1: "save,|,bold,italic,underline,strikethrough,|,sub,sup,|,justifyleft,justifycenter,justifyright,justifyfull,|,bullist,numlist,formatselect,styleselect"
    theme_advanced_buttons2: "cut,copy,paste,pastetext,pasteword,|,search,replace,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,|,insertdate,inserttime,|,pagebreak"
    theme_advanced_buttons3: "tablecontrols,|,charmap,emotions,media,|,fullscreen,code,cleanup,|,visualaid"
    theme_advanced_toolbar_location: top
    theme_advanced_toolbar_align: left
    theme_advanced_statusbar_location: bottom
    theme_advanced_resizing: 'false'
    
    file_browser_callback: tinyBrowser